### ISSUE TITLE
Upcoming talks

### ISSUE THREAD

**Issue by Nefari0uss** [OSUOSC/osuosc-website#2]
William Osler - OpenRCT2
John Markiewicz - wmultils/swn OR emacs for vim users (jmarkiewicz@airmail.cc)
Alex Fuhr - TBA
Ben Keith - Best of NICAR 2016
Nikit Malkan - KODI and media libraries
Nikit Malkan - maybe gaming on Linux.

Requests: tasker

**Comment by Nefari0uss** [comment]
Nikit & William - Linux and Open Source Gaming

Alex - BTC

Brandon - GNU/Linux History

Fuhr - Audio

Brandon & Cody - Digital Audio 

John (EDT) - Emacs for Vim users

Ben Keith - Best of NICAR 2016

Dan - Blender

Nikit & Bam - Git

Matt Curtin

Security Club

Paradigm - Bedrock Linux

Nikit - Regular Expressions 

William/Nikit -  dot file setup 

John - Bricking Android :)

**Comment by egladman** [comment]
further discussion should take place [here](https://github.com/OSUOSC/open-source-club-website/issues/158)
